const demoInventory = [
  // Snacks & Party
  {
    id: "prod_snack_chips_001",
    entityType: "PRODUCT",
    name: "Classic Salted Potato Chips",
    category: "Snacks",
    aisle: "Snacks & Party",
    price: 60,
    etaMinutes: 11,
    available: true,
    tags: ["snacks", "party", "guests", "ready-to-eat", "quick"],
    imageHint: "chips packet",
  },
  {
    id: "prod_snack_nachos_001",
    entityType: "PRODUCT",
    name: "Cheese Nachos Party Pack",
    category: "Snacks",
    aisle: "Snacks & Party",
    price: 95,
    etaMinutes: 15,
    available: true,
    tags: ["snacks", "party", "guests", "shareable", "movie"],
    imageHint: "nachos packet",
  },
  {
    id: "prod_snack_biscuits_001",
    entityType: "PRODUCT",
    name: "Assorted Cream Biscuits",
    category: "Snacks",
    aisle: "Snacks & Party",
    price: 45,
    etaMinutes: 9,
    available: true,
    tags: ["snacks", "tea", "guests", "kids", "quick"],
    imageHint: "biscuit pack",
  },
  {
    id: "prod_snack_popcorn_001",
    entityType: "PRODUCT",
    name: "Instant Butter Popcorn",
    category: "Snacks",
    aisle: "Snacks & Party",
    price: 85,
    etaMinutes: 13,
    available: true,
    tags: ["movie", "snacks", "party", "ready-to-eat"],
    imageHint: "popcorn",
  },
  {
    id: "prod_chocolate_001",
    entityType: "PRODUCT",
    name: "Assorted Chocolate Pack",
    category: "Sweets",
    aisle: "Snacks & Party",
    price: 120,
    etaMinutes: 14,
    available: true,
    tags: ["sweet", "dessert", "guests", "birthday", "delight"],
    imageHint: "chocolate",
  },
  {
    id: "prod_muffins_001",
    entityType: "PRODUCT",
    name: "Chocolate Muffins Pack of 4",
    category: "Bakery",
    aisle: "Snacks & Party",
    price: 160,
    etaMinutes: 18,
    available: true,
    tags: ["dessert", "birthday", "guests", "sweet", "snack"],
    imageHint: "muffins",
  },

  // Beverages
  {
    id: "prod_drink_cola_001",
    entityType: "PRODUCT",
    name: "Cola Bottle 750ml",
    category: "Beverages",
    aisle: "Beverages",
    price: 45,
    etaMinutes: 10,
    available: true,
    tags: ["drinks", "guests", "party", "cold beverage", "fast"],
    imageHint: "cola bottle",
  },
  {
    id: "prod_drink_juice_001",
    entityType: "PRODUCT",
    name: "Mixed Fruit Juice 1L",
    category: "Beverages",
    aisle: "Beverages",
    price: 110,
    etaMinutes: 16,
    available: true,
    tags: ["juice", "breakfast", "guests", "kids", "beverage"],
    imageHint: "juice carton",
  },
  {
    id: "prod_water_001",
    entityType: "PRODUCT",
    name: "Mineral Water Bottles Pack of 6",
    category: "Beverages",
    aisle: "Beverages",
    price: 90,
    etaMinutes: 9,
    available: true,
    tags: ["water", "travel", "guests", "hydration", "emergency"],
    imageHint: "water bottles",
  },
  {
    id: "prod_energy_drink_001",
    entityType: "PRODUCT",
    name: "Energy Drink Can",
    category: "Beverages",
    aisle: "Beverages",
    price: 115,
    etaMinutes: 13,
    available: true,
    tags: ["study", "work", "late night", "energy", "exam"],
    imageHint: "energy drink",
  },

  // Breakfast & Dairy
  {
    id: "prod_milk_001",
    entityType: "PRODUCT",
    name: "Fresh Milk 1L",
    category: "Dairy",
    aisle: "Breakfast & Dairy",
    price: 70,
    etaMinutes: 8,
    available: true,
    tags: ["breakfast", "daily essential", "milk", "fast", "tea"],
    imageHint: "milk bottle",
  },
  {
    id: "prod_bread_001",
    entityType: "PRODUCT",
    name: "Whole Wheat Bread",
    category: "Bakery",
    aisle: "Breakfast & Dairy",
    price: 55,
    etaMinutes: 9,
    available: true,
    tags: ["breakfast", "bread", "daily essential", "fast"],
    imageHint: "bread loaf",
  },
  {
    id: "prod_eggs_001",
    entityType: "PRODUCT",
    name: "Farm Eggs Pack of 6",
    category: "Breakfast",
    aisle: "Breakfast & Dairy",
    price: 90,
    etaMinutes: 14,
    available: true,
    tags: ["breakfast", "protein", "eggs", "cooking"],
    imageHint: "egg carton",
  },
  {
    id: "prod_banana_001",
    entityType: "PRODUCT",
    name: "Banana Robusta 6 pcs",
    category: "Fruits",
    aisle: "Fresh",
    price: 65,
    etaMinutes: 11,
    available: true,
    tags: ["breakfast", "fruit", "healthy", "fast", "kids"],
    imageHint: "bananas",
  },
  {
    id: "prod_cereal_001",
    entityType: "PRODUCT",
    name: "Corn Flakes Cereal",
    category: "Breakfast",
    aisle: "Breakfast & Dairy",
    price: 160,
    etaMinutes: 18,
    available: true,
    tags: ["breakfast", "cereal", "kids", "quick meal"],
    imageHint: "cereal box",
  },
  {
    id: "prod_tea_001",
    entityType: "PRODUCT",
    name: "Premium Tea Bags Pack",
    category: "Beverages",
    aisle: "Breakfast & Dairy",
    price: 140,
    etaMinutes: 16,
    available: true,
    tags: ["tea", "morning", "guests", "breakfast", "beverage"],
    imageHint: "tea box",
  },
  {
    id: "prod_coffee_001",
    entityType: "PRODUCT",
    name: "Instant Coffee Jar",
    category: "Beverages",
    aisle: "Breakfast & Dairy",
    price: 220,
    etaMinutes: 17,
    available: true,
    tags: ["coffee", "work", "study", "breakfast", "late night"],
    imageHint: "coffee jar",
  },
  {
    id: "prod_butter_001",
    entityType: "PRODUCT",
    name: "Salted Butter 100g",
    category: "Dairy",
    aisle: "Breakfast & Dairy",
    price: 62,
    etaMinutes: 12,
    available: true,
    tags: ["breakfast", "bread", "toast", "dairy"],
    imageHint: "butter",
  },

  // Serving & Party Essentials
  {
    id: "prod_cups_001",
    entityType: "PRODUCT",
    name: "Disposable Paper Cups Pack of 20",
    category: "Party Essentials",
    aisle: "Party & Serving",
    price: 75,
    etaMinutes: 12,
    available: true,
    tags: ["cups", "party", "guests", "serving", "forgotten essential"],
    imageHint: "paper cups",
  },
  {
    id: "prod_plates_001",
    entityType: "PRODUCT",
    name: "Disposable Plates Pack of 20",
    category: "Party Essentials",
    aisle: "Party & Serving",
    price: 95,
    etaMinutes: 13,
    available: true,
    tags: ["plates", "party", "guests", "serving", "birthday"],
    imageHint: "paper plates",
  },
  {
    id: "prod_spoons_001",
    entityType: "PRODUCT",
    name: "Disposable Spoons Pack of 25",
    category: "Party Essentials",
    aisle: "Party & Serving",
    price: 50,
    etaMinutes: 11,
    available: true,
    tags: ["spoons", "party", "guests", "serving", "dessert"],
    imageHint: "spoons",
  },
  {
    id: "prod_candles_001",
    entityType: "PRODUCT",
    name: "Birthday Candles Pack",
    category: "Birthday",
    aisle: "Party & Serving",
    price: 45,
    etaMinutes: 14,
    available: true,
    tags: ["birthday", "cake", "party", "forgotten essential", "surprise"],
    imageHint: "birthday candles",
  },
  {
    id: "prod_gift_wrap_001",
    entityType: "PRODUCT",
    name: "Gift Wrap Sheet",
    category: "Birthday",
    aisle: "Party & Serving",
    price: 35,
    etaMinutes: 15,
    available: true,
    tags: ["gift", "birthday", "surprise", "wrapping"],
    imageHint: "gift wrap",
  },

  // Cleaning & Home
  {
    id: "prod_tissues_001",
    entityType: "PRODUCT",
    name: "Soft Tissue Box",
    category: "Home Essentials",
    aisle: "Cleaning & Home",
    price: 65,
    etaMinutes: 9,
    available: true,
    tags: ["tissues", "guests", "cleaning", "spills", "fast"],
    imageHint: "tissue box",
  },
  {
    id: "prod_tissues_pocket_001",
    entityType: "PRODUCT",
    name: "Pocket Tissues Pack",
    category: "Personal Care",
    aisle: "Cleaning & Home",
    price: 35,
    etaMinutes: 8,
    available: true,
    tags: ["cold", "travel", "tissues", "fast", "personal care"],
    imageHint: "pocket tissues",
  },
  {
    id: "prod_cleaner_001",
    entityType: "PRODUCT",
    name: "Multipurpose Surface Cleaner",
    category: "Cleaning",
    aisle: "Cleaning & Home",
    price: 135,
    etaMinutes: 15,
    available: true,
    tags: ["cleaning", "kitchen", "home", "quick cleanup", "spill"],
    imageHint: "cleaner bottle",
  },
  {
    id: "prod_garbage_bags_001",
    entityType: "PRODUCT",
    name: "Garbage Bags Medium Roll",
    category: "Cleaning",
    aisle: "Cleaning & Home",
    price: 95,
    etaMinutes: 14,
    available: true,
    tags: ["cleaning", "garbage", "home", "waste", "forgotten essential"],
    imageHint: "garbage bags",
  },
  {
    id: "prod_microfiber_001",
    entityType: "PRODUCT",
    name: "Microfiber Cleaning Cloth Pack",
    category: "Cleaning",
    aisle: "Cleaning & Home",
    price: 120,
    etaMinutes: 12,
    available: true,
    tags: ["cleaning", "spill", "desk", "kitchen", "pet mess"],
    imageHint: "microfiber cloth",
  },
  {
    id: "prod_mop_wipes_001",
    entityType: "PRODUCT",
    name: "Floor Cleaning Wipes",
    category: "Cleaning",
    aisle: "Cleaning & Home",
    price: 145,
    etaMinutes: 16,
    available: true,
    tags: ["floor", "cleaning", "pet mess", "spill", "kitchen"],
    imageHint: "floor wipes",
  },
  {
    id: "prod_air_freshener_001",
    entityType: "PRODUCT",
    name: "Room Air Freshener Spray",
    category: "Home Care",
    aisle: "Cleaning & Home",
    price: 155,
    etaMinutes: 17,
    available: true,
    tags: ["odor", "guests", "pet mess", "room", "fresh"],
    imageHint: "air freshener",
  },

  // Health & Wellness
  {
    id: "prod_cough_drops_001",
    entityType: "PRODUCT",
    name: "Honey Lemon Cough Drops",
    category: "Wellness",
    aisle: "Health & Wellness",
    price: 50,
    etaMinutes: 13,
    available: true,
    tags: ["wellness", "cold", "sore throat", "general comfort"],
    imageHint: "cough drops",
  },
  {
    id: "prod_thermometer_001",
    entityType: "PRODUCT",
    name: "Digital Thermometer",
    category: "Health Devices",
    aisle: "Health & Wellness",
    price: 220,
    etaMinutes: 20,
    available: true,
    tags: ["wellness", "health", "fever", "monitoring"],
    imageHint: "thermometer",
  },
  {
    id: "prod_ors_001",
    entityType: "PRODUCT",
    name: "ORS Hydration Sachets",
    category: "Wellness",
    aisle: "Health & Wellness",
    price: 40,
    etaMinutes: 12,
    available: true,
    tags: ["hydration", "wellness", "heat", "general comfort"],
    imageHint: "ORS sachet",
  },
  {
    id: "prod_bandage_001",
    entityType: "PRODUCT",
    name: "Adhesive Bandages Pack",
    category: "First Aid",
    aisle: "Health & Wellness",
    price: 55,
    etaMinutes: 10,
    available: true,
    tags: ["first aid", "cut", "minor injury", "emergency"],
    imageHint: "bandage",
  },
  {
    id: "prod_sanitizer_001",
    entityType: "PRODUCT",
    name: "Hand Sanitizer 100ml",
    category: "Hygiene",
    aisle: "Health & Wellness",
    price: 60,
    etaMinutes: 9,
    available: true,
    tags: ["hygiene", "travel", "guests", "health", "fast"],
    imageHint: "sanitizer",
  },

  // Baby Care
  {
    id: "prod_baby_wipes_001",
    entityType: "PRODUCT",
    name: "Baby Wipes 72 pcs",
    category: "Baby Care",
    aisle: "Baby Care",
    price: 120,
    etaMinutes: 12,
    available: true,
    tags: ["baby", "wipes", "diaper", "forgotten essential"],
    imageHint: "baby wipes",
  },
  {
    id: "prod_diapers_001",
    entityType: "PRODUCT",
    name: "Baby Diapers Medium Pack",
    category: "Baby Care",
    aisle: "Baby Care",
    price: 360,
    etaMinutes: 17,
    available: true,
    tags: ["baby", "diapers", "urgent"],
    imageHint: "diaper pack",
  },
  {
    id: "prod_baby_lotion_001",
    entityType: "PRODUCT",
    name: "Baby Lotion",
    category: "Baby Care",
    aisle: "Baby Care",
    price: 180,
    etaMinutes: 18,
    available: true,
    tags: ["baby", "lotion", "care", "skin"],
    imageHint: "baby lotion",
  },

  // Personal Care
  {
    id: "prod_deodorant_001",
    entityType: "PRODUCT",
    name: "Fresh Deodorant Spray",
    category: "Personal Care",
    aisle: "Personal Care",
    price: 199,
    etaMinutes: 16,
    available: true,
    tags: ["interview", "grooming", "personal care", "work"],
    imageHint: "deodorant",
  },
  {
    id: "prod_face_wipes_001",
    entityType: "PRODUCT",
    name: "Refreshing Face Wipes",
    category: "Personal Care",
    aisle: "Personal Care",
    price: 90,
    etaMinutes: 11,
    available: true,
    tags: ["grooming", "travel", "interview", "freshen up"],
    imageHint: "face wipes",
  },
  {
    id: "prod_toothbrush_001",
    entityType: "PRODUCT",
    name: "Travel Toothbrush",
    category: "Personal Care",
    aisle: "Personal Care",
    price: 55,
    etaMinutes: 13,
    available: true,
    tags: ["travel", "hygiene", "forgot", "personal care"],
    imageHint: "toothbrush",
  },
  {
    id: "prod_sanitary_pads_001",
    entityType: "PRODUCT",
    name: "Sanitary Pads Pack",
    category: "Personal Care",
    aisle: "Personal Care",
    price: 95,
    etaMinutes: 12,
    available: true,
    tags: ["period", "personal care", "urgent", "hygiene"],
    imageHint: "sanitary pads",
  },
  {
    id: "prod_mints_001",
    entityType: "PRODUCT",
    name: "Fresh Breath Mints",
    category: "Personal Care",
    aisle: "Personal Care",
    price: 45,
    etaMinutes: 8,
    available: true,
    tags: ["interview", "meeting", "guests", "fresh", "forgotten essential"],
    imageHint: "mints",
  },

  // Work, Study & Electronics
  {
    id: "prod_phone_charger_001",
    entityType: "PRODUCT",
    name: "USB-C Fast Charger 20W",
    category: "Electronics Accessories",
    aisle: "Work & Electronics",
    price: 499,
    etaMinutes: 21,
    available: true,
    tags: ["charger", "work", "meeting", "electronics", "urgent"],
    imageHint: "phone charger",
  },
  {
    id: "prod_power_bank_001",
    entityType: "PRODUCT",
    name: "10000mAh Power Bank",
    category: "Electronics Accessories",
    aisle: "Work & Electronics",
    price: 999,
    etaMinutes: 24,
    available: true,
    tags: ["power cut", "travel", "phone", "emergency", "charging"],
    imageHint: "power bank",
  },
  {
    id: "prod_notebook_001",
    entityType: "PRODUCT",
    name: "A5 Notebook",
    category: "Office",
    aisle: "Work & Electronics",
    price: 80,
    etaMinutes: 13,
    available: true,
    tags: ["office", "interview", "meeting", "notes", "study"],
    imageHint: "notebook",
  },
  {
    id: "prod_pen_001",
    entityType: "PRODUCT",
    name: "Ball Pens Pack of 5",
    category: "Office",
    aisle: "Work & Electronics",
    price: 50,
    etaMinutes: 10,
    available: true,
    tags: ["office", "interview", "meeting", "study", "forgotten essential"],
    imageHint: "pens",
  },
  {
    id: "prod_sticky_notes_001",
    entityType: "PRODUCT",
    name: "Sticky Notes Pad",
    category: "Office",
    aisle: "Work & Electronics",
    price: 75,
    etaMinutes: 12,
    available: true,
    tags: ["study", "office", "project", "planning"],
    imageHint: "sticky notes",
  },
  {
    id: "prod_usb_cable_001",
    entityType: "PRODUCT",
    name: "USB-C Charging Cable",
    category: "Electronics Accessories",
    aisle: "Work & Electronics",
    price: 199,
    etaMinutes: 16,
    available: true,
    tags: ["charger", "cable", "electronics", "work", "travel"],
    imageHint: "USB cable",
  },

  // Emergency, Weather & Power Cut
  {
    id: "prod_umbrella_001",
    entityType: "PRODUCT",
    name: "Compact Umbrella",
    category: "Rain Essentials",
    aisle: "Emergency & Weather",
    price: 299,
    etaMinutes: 19,
    available: true,
    tags: ["rain", "umbrella", "weather", "urgent"],
    imageHint: "umbrella",
  },
  {
    id: "prod_torch_001",
    entityType: "PRODUCT",
    name: "LED Torch Light",
    category: "Emergency",
    aisle: "Emergency & Weather",
    price: 180,
    etaMinutes: 18,
    available: true,
    tags: ["power cut", "light", "emergency", "night"],
    imageHint: "torch",
  },
  {
    id: "prod_batteries_001",
    entityType: "PRODUCT",
    name: "AA Batteries Pack of 4",
    category: "Emergency",
    aisle: "Emergency & Weather",
    price: 90,
    etaMinutes: 14,
    available: true,
    tags: ["battery", "torch", "remote", "power cut", "emergency"],
    imageHint: "batteries",
  },
  {
    id: "prod_mosquito_repellent_001",
    entityType: "PRODUCT",
    name: "Mosquito Repellent Spray",
    category: "Home Care",
    aisle: "Emergency & Weather",
    price: 160,
    etaMinutes: 17,
    available: true,
    tags: ["mosquito", "night", "power cut", "comfort"],
    imageHint: "mosquito repellent",
  },
  {
    id: "prod_raincoat_001",
    entityType: "PRODUCT",
    name: "Disposable Rain Poncho",
    category: "Rain Essentials",
    aisle: "Emergency & Weather",
    price: 120,
    etaMinutes: 16,
    available: true,
    tags: ["rain", "travel", "weather", "urgent"],
    imageHint: "rain poncho",
  },

  // Pet Care
  {
    id: "prod_pet_wipes_001",
    entityType: "PRODUCT",
    name: "Pet Cleaning Wipes",
    category: "Pet Care",
    aisle: "Pet Care",
    price: 160,
    etaMinutes: 15,
    available: true,
    tags: ["pet", "dog", "cat", "cleaning", "mess"],
    imageHint: "pet wipes",
  },
  {
    id: "prod_pet_food_001",
    entityType: "PRODUCT",
    name: "Dry Pet Food Small Pack",
    category: "Pet Care",
    aisle: "Pet Care",
    price: 240,
    etaMinutes: 18,
    available: true,
    tags: ["pet", "dog", "cat", "food", "urgent"],
    imageHint: "pet food",
  },
  {
    id: "prod_pet_odour_001",
    entityType: "PRODUCT",
    name: "Pet Odour Control Spray",
    category: "Pet Care",
    aisle: "Pet Care",
    price: 220,
    etaMinutes: 19,
    available: true,
    tags: ["pet", "odor", "cleaning", "mess"],
    imageHint: "pet odour spray",
  },

  // Travel & Packing
  {
    id: "prod_travel_pouch_001",
    entityType: "PRODUCT",
    name: "Small Travel Pouch",
    category: "Travel",
    aisle: "Travel Essentials",
    price: 180,
    etaMinutes: 22,
    available: true,
    tags: ["travel", "packing", "trip", "organize"],
    imageHint: "travel pouch",
  },
  {
    id: "prod_safety_pins_001",
    entityType: "PRODUCT",
    name: "Safety Pins Pack",
    category: "Travel",
    aisle: "Travel Essentials",
    price: 35,
    etaMinutes: 10,
    available: true,
    tags: ["travel", "clothes", "emergency", "repair", "packing"],
    imageHint: "safety pins",
  },
  {
    id: "prod_tape_001",
    entityType: "PRODUCT",
    name: "Transparent Tape Roll",
    category: "Stationery",
    aisle: "Travel Essentials",
    price: 40,
    etaMinutes: 11,
    available: true,
    tags: ["packing", "project", "repair", "gift", "tape"],
    imageHint: "tape",
  },
  {
    id: "prod_scissors_001",
    entityType: "PRODUCT",
    name: "Small Scissors",
    category: "Stationery",
    aisle: "Travel Essentials",
    price: 75,
    etaMinutes: 15,
    available: true,
    tags: ["project", "packing", "gift", "office"],
    imageHint: "scissors",
  },

  // Kitchen & Quick Meals
  {
    id: "prod_instant_noodles_001",
    entityType: "PRODUCT",
    name: "Instant Noodles Pack",
    category: "Quick Meals",
    aisle: "Kitchen & Quick Meals",
    price: 60,
    etaMinutes: 10,
    available: true,
    tags: ["quick meal", "late night", "student", "hungry", "fast"],
    imageHint: "instant noodles",
  },
  {
    id: "prod_pasta_001",
    entityType: "PRODUCT",
    name: "Pasta 500g",
    category: "Kitchen",
    aisle: "Kitchen & Quick Meals",
    price: 120,
    etaMinutes: 18,
    available: true,
    tags: ["cooking", "dinner", "pasta", "meal"],
    imageHint: "pasta",
  },
  {
    id: "prod_pasta_sauce_001",
    entityType: "PRODUCT",
    name: "Tomato Pasta Sauce",
    category: "Kitchen",
    aisle: "Kitchen & Quick Meals",
    price: 150,
    etaMinutes: 17,
    available: true,
    tags: ["cooking", "dinner", "pasta", "sauce"],
    imageHint: "pasta sauce",
  },
  {
    id: "prod_cheese_001",
    entityType: "PRODUCT",
    name: "Processed Cheese Slices",
    category: "Dairy",
    aisle: "Kitchen & Quick Meals",
    price: 140,
    etaMinutes: 16,
    available: true,
    tags: ["cooking", "breakfast", "pasta", "sandwich", "cheese"],
    imageHint: "cheese",
  },

  // Laundry
  {
    id: "prod_detergent_001",
    entityType: "PRODUCT",
    name: "Laundry Detergent Liquid",
    category: "Laundry",
    aisle: "Laundry",
    price: 210,
    etaMinutes: 20,
    available: true,
    tags: ["laundry", "clothes", "cleaning", "stain"],
    imageHint: "detergent",
  },
  {
    id: "prod_stain_remover_001",
    entityType: "PRODUCT",
    name: "Fabric Stain Remover",
    category: "Laundry",
    aisle: "Laundry",
    price: 160,
    etaMinutes: 18,
    available: true,
    tags: ["stain", "clothes", "coffee spill", "laundry"],
    imageHint: "stain remover",
  },
];

module.exports = demoInventory;
